---
title: "Project Proposal"
date: "4/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Team Members:  John Nownes, Sonia Thomas, Yi Hang Khor, and Kobe Pranivong
#### Project Coordinator: John Nownes
## Data Set
https://www.kaggle.com/sudalairajkumar/covid19-in-usa#us_states_covid19_daily.csv

## Motivation of Study
The dataset we chose for our project looks at the newly-discovered novel coronavirus, which causes coronavirus disease, COVID-19.  With nearly all parts of life here in the US and most places around the globe having been affected by the pandemic, it is already easily the most disruptive disease since the Spanish Flu of 1918. On top of the dangerously high number of deaths currently being predicted, the “social distancing” procedures being implemented to slow the spread of coronavirus appear to be pointing the economy towards a serious economic recession the effects of which may still be felt years from now. Until a vaccine is widely available, it appears that this coronavirus pandemic will be the most important factor affecting the livelihood of nearly every person in this country for several months, and for this reason it is a worthwhile project to study.


## Overview of Data Set
The author of the dataset is Sudalai Rajkumar, a popular and highly-rated contributor on Kaggle. Below is his LinkedIn, which displays some of his most impressive accomplishments. From a credibility standpoint, we are reasonably confident that Mr. Rajkumar’s data on the coronavirus is among the most accurate and thorough data sets available to the public.
https://www.linkedin.com/in/sudalairajkumar/?originalSubdomain=in

Within Mr. Rajkumar’s coronavirus Kaggle page, there are two different .csv files updated daily. One is a file containing coronavirus statistics on the US national level, and the other .csv file contains coronavirus statistics at the US state level. We will be studying the latter file, the .csv file concerning the state-level statistics. We chose the state-level dataset because of our desire to look more closely at the individual states, especially since this pandemic varies widely by location. We also know that there has been a range of different policies put in place at the state level, and we plan to study the relationship between states’ policies such as implementing a “Stay at home” order and the number of reported cases and deaths.

Looking specifically at our state-level .csv file, we see immediately that the data set is arranged in a “tidy” format, since each observation includes the date of the observation and the state, making these the two keys for that row. As you move along the columns, there are statistics on tests performed cumulatively and on that day, as well as the number of each result (positive, negative, and pending). Additionally, we can see the number of deaths, hospitalizations, recoveries, and ventilators being used.

## Plan for Exploratory Analysis